Feature: Command Line | --file

Example: --file runs the given file
    When running clox with "--file features/commandline/test.lox"
    Then clox prints to stdout:
    ```
    "abc"
    ```

Example: When no file is given
    When running clox with "--file"
    Then clox fails with:
    ```
    Specify file to run after --file

    Usage: clox [FLAGS]
    Usage: clox [FLAGS] --repl
    Usage: clox [FLAGS] --eval "expression"
    Usage: clox [FLAGS] --file path/to/file

    Flags:
        --bytecode     Print generated bytecode
        --help         Print this message
        --memory       Show contents of the clox-heap while tracing
        --no-run       Do not run the program
        --trace        Show execution of each instruction and state of the stack
    ```

Example: When the file does not exist
    When running clox with "--file features/commandline/no-such-file.lox"
    Then clox fails with:
    ```
    Could not open file "features/commandline/no-such-file.lox".
    ```
