Feature: Command Line | --help

Example: --help prints the help
    When running clox with "--help"
    Then clox prints to stdout:
    ```
    Usage: clox [FLAGS]
    Usage: clox [FLAGS] --repl
    Usage: clox [FLAGS] --eval "expression"
    Usage: clox [FLAGS] --file path/to/file
    
    Flags:
        --bytecode     Print generated bytecode
        --help         Print this message
        --memory       Show contents of the clox-heap while tracing
        --no-run       Do not run the program
        --trace        Show execution of each instruction and state of the stack
    ```           
