#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "debug.h"
#include "common.h"
#include "compiler.h"
#include "vm.h"

CloxRun cloxRun;

// Mode 1: read–eval–print loop
static void repl(){
    initVM();

    char line[1024];
    for (;;){
        printf("> ");

        if (!fgets(line, sizeof(line), stdin)){
            printf("\n");
            break;
        }

        if (memcmp(line, "quit", 4)==0){
            break;
        }
        else {
            interpret(line);
        }
    }

    freeVM();
    exit(0);
}

static char* readFile(const char* path){
    FILE* file = fopen(path, "rb");
    if (file == NULL){
        fprintf(stderr, "Could not open file \"%s\".\n", path);
        exit(74);
    }

    fseek(file, 0L, SEEK_END);
    size_t fileSize = ftell(file);
    rewind(file);

    char* buffer = (char*)malloc(fileSize+1);
    if (buffer == NULL){
        fprintf(stderr, "Not enough memory to read \"%s\"\n", path);
        exit(74);
    }
    size_t bytesRead = fread(buffer, sizeof(char), fileSize, file);
    if (bytesRead < fileSize){
        fprintf(stderr, "Could not read \"%s\".\n", path);
        exit(74);
    }
    buffer[bytesRead] = '\0';

    fclose(file);
    return buffer;
}

// Mode 2: run a file
static void runFile(const char* path){
    char* source = readFile(path);
    initVM();
    InterpretResult result = interpret(source);
    freeVM();
    free(source);

    if (result == INTERPRET_COMPILE_ERROR) exit(65);
    if (result == INTERPRET_RUNTIME_ERROR) exit(70);
}

// Mode 3: Evaluate an expression from the command line.
static void eval(const char* expression){
    initVM();
    InterpretResult result = interpret(expression);
    freeVM();
    if (result == INTERPRET_COMPILE_ERROR) exit(65);
    if (result == INTERPRET_RUNTIME_ERROR) exit(70);
}

static void fprintUsage(FILE* stream){
    fprintf(stream, "Usage: clox [FLAGS]\n");
    fprintf(stream, "Usage: clox [FLAGS] --repl\n");
    fprintf(stream, "Usage: clox [FLAGS] --eval \"expression\"\n");
    fprintf(stream, "Usage: clox [FLAGS] --file path/to/file\n");
    fprintf(stream, "\nFlags:\n");
    fprintf(stream, "    --bytecode     Print generated bytecode\n");
    fprintf(stream, "    --help         Print this message\n");
    fprintf(stream, "    --memory       Show contents of the clox-heap while tracing\n");
    fprintf(stream, "    --no-run       Do not run the program\n");
    fprintf(stream, "    --trace        Show execution of each instruction and state of the stack\n");
}

int main(int argc, const char* argv[]){
    // Scan for known command line flags
    for (int i=1; i<argc; i++){
        if (memcmp(argv[i], "--bytecode", 10) == 0){ 
            cloxRun.showBytecode = true; 
            cloxRun.noExecution = true;
            cloxRun.printResultVerbose = true; 
        }
        else if (memcmp(argv[i], "--eval", 6) == 0){ 
            cloxRun.eval = true; 
            cloxRun.evalExpressionIndex = i + 1; 
            cloxRun.printResult = true;  
        }
        else if (memcmp(argv[i], "--help", 6) == 0){ 
            cloxRun.help = true; 
        }
        else if (memcmp(argv[i], "--file", 6) == 0){ 
            cloxRun.file = true; 
            cloxRun.filePathIndex = i + 1;
            cloxRun.printResult = true;  
        }
        else if (memcmp(argv[i], "--memory", 8) == 0){ 
            cloxRun.traceExecution = true; 
            cloxRun.traceMemory = true; 
            cloxRun.printResultVerbose = true;
        }
        else if (memcmp(argv[i], "--no-run", 8) == 0){ 
            cloxRun.noExecution = true; 
        }
        else if (memcmp(argv[i], "--repl", 7) == 0){ 
            cloxRun.repl = true; 
            cloxRun.printResult = true;
        }
        else if (memcmp(argv[i], "--trace", 7) == 0){ 
            cloxRun.traceExecution = true; 
            cloxRun.printResultVerbose = true;
        }
        else if (memcmp(argv[i], "--", 2) == 0){
            fprintf(stderr, "Unknown command line flag: %s.\n\n", argv[i]);
            fprintUsage(stderr);
            exit(64);
        }
    }

    // Check for --help
    if (cloxRun.help){
        fprintUsage(stdout);
        exit(0);
    }
    
    // Check that exactly 1 run mode is selected
    int selected = 0;
    if (cloxRun.eval) selected += 1;
    if (cloxRun.file) selected += 1;
    if (cloxRun.repl) selected += 1;
    if (selected == 0){
        cloxRun.repl = true;
    }
    if (selected > 1){
        fprintf(stderr, "More than one option out of [--eval, --file, --repl] given. Dunno what you want.\n");
        exit(64);
    }

    // Check for non-sensical combinations
    if (cloxRun.noExecution && cloxRun.traceExecution){
        fprintf(stderr, "Combining --trace with --no-run makes no sense.\n");
        exit(64);
    }

    // Switch to the desired run mode
    if (cloxRun.eval){
        if (cloxRun.evalExpressionIndex < argc){
            eval(argv[cloxRun.evalExpressionIndex]);
        } 
        else {
            fprintf(stderr, "Specify expression to evaluate after --eval\n\n");
            fprintUsage(stderr);
            exit(64);
        }
    } 
    if (cloxRun.file){
        if (cloxRun.filePathIndex < argc){
            runFile(argv[cloxRun.filePathIndex]);
        }
        else {
            fprintf(stderr, "Specify file to run after --file\n\n");
            fprintUsage(stderr);
            exit(64);
        }
    } 
    if (cloxRun.repl){ 
        repl();
    }

    return 0;
}